---
- hosts: Servers
  tasks:
  - name: Install maven on the production server
    sudo: true
    apt: pkg=maven state=installed update_cache=true

  - name: Install git on the production server
    sudo: true
    apt: pkg=git state=installed update_cache=true
